name: Java CI

on:
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK 25
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '25'
          distribution: 'temurin'

      - uses: burrunan/gradle-cache-action@v3.0.1
        name: Build BiomeTool
        with:
          arguments: build
          gradle-version: wrapper
          properties: |
            kotlin.js.compiler=ir
            kotlin.parallel.tasks.in.project=true

      - name: Upload PR distribution zip
        uses: actions/upload-artifact@v4
        with:
          name: BiomeTool-PR-${{ github.event.pull_request.number }}-${{ github.sha }}
          path: build/libs/BiomeTool-*.zip
